import Header from '@/components/header';
import Footer from '@/components/footer';

export const metadata = {
    title: 'Plantswap',
    description: 'Generated by create next app',
}

export default function MainLayout({ children }) {
    return (
        <>
            <Header>
                <h1>{metadata.title}</h1>
            </Header>
            <main>
                {children}
            </main>
            <Footer />
        </>
    )
}