'use client';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { motion } from 'framer-motion';

export const metadata = {
    title: 'Plantswap',
    description: 'Generated by create next app',
}

export default function MainLayout({ children }) {
    return (
        <>
            <Header>
                <h1>{metadata.title}</h1>
            </Header>
            <motion.main
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5 }}
                exit={{ opacity: 0 }}
                >
                {children}
            </motion.main> 
            <Footer />
        </>
    )
}