'use client';
import Footer from '@/components/footer';
import MotionContainer from '@/components/common/motion';

export const metadata = {
    title: 'Plantswap',
    description: 'Generated by create next app',
}

export default function MainLayout({ children }) {
    return (
        <>
            <MotionContainer tag='main'>
                {children}
            </MotionContainer>
            <Footer />
        </>
    )
}