import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'
// import Styles from '@/styles/app.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Plantswap',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={inter.className}>
        <main>
            {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
